;;; geiser-sexp7-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "geiser-sexp7" "geiser-sexp7.el" (0 0
;;;;;;  0 0))
;;; Generated autoloads from geiser-sexp7.el

(autoload 'connect-to-sexp7 "geiser-sexp7" "\
Start a Godot s7 REPL connected to a remote process.

Start a Scheme Repl in the active Godot s7 scene." t)

(geiser-activate-implementation 'sexp7)

(autoload 'run-sexp7 "geiser-sexp7" "\
Start a Geiser Godot s7 REPL." t)

(autoload 'switch-to-sexp7 "geiser-sexp7" "\
Start a Geiser Godot s7 REPL, or switch to a running one." t)

(register-definition-prefixes "geiser-sexp7" '("geiser-sexp7-" "sexp7"))

;;;***

;;; End of scraped data

(provide 'geiser-sexp7-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-sexp7-autoloads.el ends here
